Fix changed-files error and optimize PR check

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -47,3 +47,56 @@ jobs:
               -k https://wolfi.duyne.me/wolfi-melange.rsa.pub \
               $file
           done
+
+
+name: Pull Request Check
+
+on:
+  pull_request:
+    paths:
+      - "*.yaml"
+
+jobs:
+  lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Lint using Wolfictl
+        uses: wolfi-dev/actions/wolfictl-lint@main
+
+  build:
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/wolfi-dev/sdk:latest
+      options: --cap-add NET_ADMIN --cap-add SYS_ADMIN --device /dev/fuse --security-opt seccomp=unconfined --security-opt apparmor=unconfined
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Look for changed files
+        id: changes
+        uses: tj-actions/changed-files@v46
+        with:
+          files_yaml: |
+            melange:
+              - ./*.yaml
+
+      - name: Build all packages
+        if: steps.changes.outputs.melange_all_changed_files != ''
+        run: |
+          for file in ${{ steps.changes.outputs.melange_all_changed_files }}; do
+            if [[ $file == ".yam.yaml" ]]; then
+              continue
+            fi
+            melange build \
+              --arch x86_64 \
+              -r https://packages.wolfi.dev/os \
+              -k https://packages.wolfi.dev/os/wolfi-signing.rsa.pub \
+              -r https://wolfi.duyne.me \
+              -k https://wolfi.duyne.me/wolfi-melange.rsa.pub \
+              --log-level debug \
+              $file || { echo "Build failed for $file"; exit 1; }
+          done
