feat: update new structure

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -3,7 +3,10 @@ name: Pull Request Check
 on:
   pull_request:
     paths:
-      - "*.yaml"
+      - "**/*.yaml"
+      - "!.github/**/*.yaml"
+      - "!images/**/*.yaml"
+      - "!examples/**/*.yaml"
 permissions:
   contents: read
   pull-requests: read
@@ -28,24 +31,29 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Generate key
+        run: make init
+
       - name: Look for changed files
         id: changes
         uses: tj-actions/changed-files@v47
         with:
           files_yaml: |
             melange:
-              - ./*.yaml
+              - '**/*.yaml'
+              - '!.github/**/*.yaml'
+              - '!images/**/*.yaml'
+              - '!examples/**/*.yaml'
 
       - name: Build all packages
         if: steps.changes.outputs.melange_all_changed_files != ''
         run: |
           for file in ${{ steps.changes.outputs.melange_all_changed_files }}; do
-            melange build \
-              --arch x86_64 \
-              -r https://packages.wolfi.dev/os \
-              -k https://packages.wolfi.dev/os/wolfi-signing.rsa.pub \
-              -r https://wolfi.duyne.me \
-              -k https://wolfi.duyne.me/wolfi-melange.rsa.pub \
-              --log-level debug \
-              $file || { echo "Build failed for $file"; exit 1; }
+            if [[ -z "$file" ]] || [[ ! -f "$file" ]]; then
+              continue
+            fi
+            packageName=$(basename $(dirname "$file"))
+            echo "Building package: $packageName"
+            make package/"${packageName}" || { echo "Build failed for $packageName"; exit 1; }
+            make test/"${packageName}" || { echo "Test failed for $packageName"; exit 1; }
           done
